# Generated by Django 5.1.6 on 2025-02-24 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='title',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='body',
        ),
    ]
