# Generated by Django 5.1.6 on 2025-02-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_title_tasks_task_remove_tasks_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='task',
            new_name='title',
        ),
        migrations.AddField(
            model_name='tasks',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
